# This is a basic workflow to help you get started with Actions

name: Newman CLI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create dirct
          run:|
          mkdir SampleArtifact

      # Install node.js
      - name: Install node
      - uses: actions/checkout@v4
        with:
           node-version: '22.12.0'

      # Install newman 
      - name: Install Newman
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      #Run collection
      - name: Run collection
        run: |
            newman run "Response_validation.postman_collection.json" -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html

     #Publish the report
      - name: Publish report
      - uses: actions/upload-artifact@v4
        with:
         name: Reports
         path: SampleArtifact
