name: Newman CLI

on: 
 push:
  branches: [ "main" ]
 workflow_dispatch:
   
jobs:
  test-api:
   runs-on: windows-latest
   
   steps:
      - uses: actions/checkout@v4
      - name: Create dir
          run:|
          mkdir SampleArtifact

      # Install node.js
      - name: Install node
      - uses: actions/checkout@v4
        with:
           node-version: '20'

      # Install newman 
      - name: Install Newman
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      #Run collection
      - name: Run collection
        run: newman run "Response_validation.postman_collection.json" -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html

     #Publish the report
      - name: Publish report
      - uses: actions/upload-artifact@v4
        with:
         name: Reports
         path: SampleArtifact
