name: Run Postman Tests and Generate HTML Report
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  postman-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Install Newman and HTML Extra Reporter
        run: npm install -g newman newman-reporter-htmlextra
 
      - name: Run Postman Tests and Generate HTML Report
        run: newman run https://github.com/sampleapm/test/blob/main/Response_validation.postman_collection.json --reporters=htmlextra --reporter-htmlextra-export=test-report.html
 
      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: test-report.html
