name: Run Postman Collection
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  test-api:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
 
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra
         npm install -g @faker-js/faker@latest
         npm install -g uuid@latest
 
      - name: Run Postman Collection
        run: newman run Response_validation.postman_collection.json -r htmlextra
