name: Run Postman Tests and Generate HTML Report
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  postman-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Install Newman and HTML Extra Reporter
        run: npm install -g newman newman-reporter-htmlextra
 
      - name: Run Postman Tests and Generate HTML Report
        run: newman run Response_validation.postman_collection.json -r htmlextra
 
      
